@startuml SalitrePass

    skinparam style strictuml
    skinparam defaultTextAlignment center

    title Diagrama de Flujo:\nConducta de las Personas con SalitrePass

    start 
        :Persona ingresa al parque;
        repeat :Persona entra al centro;
            if (Persona elije si desea realizar una actividad o\nhacer una fila para una atracción) then (Atracción)
                    :Gira la ruleta para realizar\nla selección de que atracción\nse va revisar;
                    if (¿La atracción tiene SalitrePass?) then (Sí)
                        if (¿Es el tiempo de espera de la\nfila de SalitrePass es menor\nal de la fila normal?) then (Sí)
                            :La persona se une a la fila\nde SalitrePass;
                        else (No)
                            :La persona se une a la fila\nnormal;
                        endif
                    else (No)
                        if (¿El tiempo de espera es menor que el\nmáximo tiempo de espera?) then (Sí)
                            :La persona se una a fila normal;
                        else (No)
                    endif
                    endif
            else (Actividad)
                    :Se gira la ruleta para\nseleccionar la actividad;
            endif
        repeat while (¿Hora de irse?) is (No) 
        -> Sí;
    stop


@enduml